### ISSUE TITLE
White Globe - Material Failed to load.

### ISSUE THREAD

**Issue by syntax-sage** [Harshal0902/Three.js-example#1]
Hey :)

Love this project, tried to incorporate it into my own. 
Grateful to you for making this.

ISSUE:
Using Next JS 13
Globe loads fine.
No material - Globe is just white no texture/material rendered.

Anyway of fixing this issue?

I am hosting it here:
[https://vercel.com/syntax-sage/sage-dev-app-2](url)

Feel free to have a look at the project and let me know if you can see anything I did wrong.

Link to github Repo:
[https://github.com/syntax-sage/sage-dev-app-2](url)

**Comment by Harshal0902** [comment]
Didi you copied the textures folder along with the 3d model?

**Comment by syntax-sage** [comment]
yes i did, i also checked the folder structure to make sure it was similar to yours, Have a look at my GitHub repo

**Comment by syntax-sage** [comment]
I wonder if it doesn't have something to do with the way nexts js 13 references the public folder now?

**Comment by Harshal0902** [comment]
> yes i did, i also checked the folder structure to make sure it was similar to yours, Have a look at my GitHub repo

The repo link is incorrect, can you share the correct one once again?

**Comment by syntax-sage** [comment]
https://github.com/syntax-sage/sage-dev-app-2

**Comment by syntax-sage** [comment]
should work now

**Comment by Harshal0902** [comment]
Still showing 404 page. Make sure it is public.

**Comment by syntax-sage** [comment]
oh gosh lol its public now sorry

**Comment by syntax-sage** [comment]
i just cloned your repo and it works fine, so must be bug with the new next 13

**Comment by Harshal0902** [comment]
The issue is not due to Next 13, sometime three.js version doesn't works with react 18.

Run following commands, this will resolve the issue:

```
npm uninstall @react-three/drei @react-three/fiber three

npm install @react-three/drei@7.22.6 @react-three/fiber@7.0.19 three@0.134.0
```

**Comment by syntax-sage** [comment]
Bro you are a legend, God Bless you !!! It worked !!

**Comment by syntax-sage** [comment]
Bro download Brave browser and activate the wallet then i can tip you :)

**Comment by Harshal0902** [comment]
Thank you @syntax-sage I appreciate that you thought of me, but you don't have to tip me, I am happy to help you, and best of luck!
